---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - logcollector.iffq.top
  resources:
  - logstreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logcollector.iffq.top
  resources:
  - logstreams/finalizers
  verbs:
  - update
- apiGroups:
  - logcollector.iffq.top
  resources:
  - logstreams/status
  verbs:
  - get
  - patch
  - update
