apiVersion: logcollector.iffq.top/v1alpha1
kind: LogStream
metadata:
  name: logstream-sample
spec:
  # TODO(user): Add fields here
  podSeletor:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - nginx
            - nginx2
  fluentBit:
    - path: xxx
